def mensajes_por_idioma(idioma_i):
    #Cambia el idioma de la interfaz
    match idioma_i:
        case 1:{"soporte_cliente": "Customer Support",
            "x": "Enter the text to analyze: ",
            "y" : "is present in",
            "z" :"%" "of the text, you use it too much, look for replacement synonyms :c.",
            "a" :"%" "of the text, you should look for some synonym for that word :c.",
            "b": "%" "of the text, you do not use it as often, but you could make some changes.",
            "d" : "%" "of the text, you don't use it very often :D.",
            "e" : "Your text has a varied vocabulary and a fluid writing style.",
            "f": "Some words appear more than others, but it's not problematic, it's normal in texts with repeated key terms.",
            "g" : "There are words that appear with a frequency much higher than the rest, which may indicate redundancy or lack of variety in vocabulary.",
            "h" : "Total words: ",
            "j" : "Total letters: ",
            "k" : "Total sentences: ",
            "l" : "Select a PDF file",
            "m" : "PDF file",
            "n" : "Enter 1 for text or 2 for PDF",
            "no" : "No language detected",
            "p" : "Error processing PDF",
            "q" : "Invalid option; try 1 or 2",
            "id_sinonimos" : 1}
        case 2:
            return {"soporte_cliente": "Soporte al cliente",
            "x" : "Ingrese el texto a analizar: ",
            "y" : "está presente en el",
            "z" : "%" "del texto, la usas demasiado, busca sinónimos de reemplazo :c.",
            "a" : "%"" del texto, deberías buscar algún sinónimo para dicha palabra :c.",
            "b" : "%" "del texto, no lo usas con tanta frecuencia, pero podrías realizar algún cambio.",
            "d" : "%"" del texto, no lo usas con mucha frecuencia :D.",
            "e" : "Tu texto tiene un vocabulario variado y un estilo de escritura fluido.",
            "f" : "Algunas palabras aparecen más que otras, pero no es problemático, es normal en textos con términos clave repetidos.",
            "g" : "Hay palabras que aparecen con una frecuencia muy superior al resto, puede indicar redundancia o falta de variedad en el vocabulario.",
            "h" : "Total de palabras: ",
            "j" : "Total de letras: ",
            "k" : "Total de frases: ",
            "l" : "Selecciona un archivo PDF",
            "m" : "Archivos PDF",
            "n" : "Ingrese 1 para texto, y 2 para pdf",
            "no" : "No se detectó idioma",
            "p" : "Error al procesar el PDF:",
            "q" : "Opción no válida. Intente con 1 o 2.",
            "id_sinonimos" : 2,}
        case 3:
            return {"soporte_cliente": "Suporte ao cliente",
            "x" : "Digite o texto a ser analisado: ",
            "y" : "está presente em",
            "z" : "%" "do texto, você a usa demais, procure sinônimos de substituição :c.",
            "a" : "%" "do texto, você deveria procurar algum sinônimo para essa palavra :c.",
            "b" : "%" "do texto, você não o usa com tanta frequência, mas poderia fazer alguma alteração.",
            "d" : "%" "del texto, você não o usa com muita frequência :D.",
            "e" : "Seu texto tem um vocabulário variado e um estilo de escritura fluido.",
            "f" : "Algumas palavras aparecem mais do que outras, mas não é problemático, é normal em textos com termos-chave repetidos.",
            "g" : "Há palavras que aparecem com uma frequência muito superior ao resto, isso pode indicar redundância ou falta de variedade no vocabulário.",
            "h" : "Total de palavras: ",
            "j" : "Total de letras: ",
            "k" : "Total de frases: ",
            "l" : "Selecione um arquivo PDF",
            "m" : "Arquivo PDF",
            "n" : "Digite 1 para texto ou 2 para PDF",
            "o" : "Nenhum arquivo selecionado",
            "p" : "Erro ao processar o PDF",
            "q" : "Opção inválida; tente 1 ou 2",
            "id_sinonimos" : 3}
        case 4:
            return {"soporte_cliente": "カスタマーサポート",
            "x" : "分析するテキストを入力してください: ",
            "y" : "テキストの",
            "z" : "% に存在します。使いすぎです。代替の同義語を探してください。:c",
            "a" : "% に存在しているので、同義語を探すべきです。:c",
            "b" : "% に存在しますが、それほど頻繁に使用していませんが、いくつかの変更を行うことができるかもしれません。",
            "d" : "% に存在していますが、あまり頻繁には使いません。 :D",
            "e" : "あなたのテキストは多様な語彙と流れるような文体を持っています。",
            "f" : "いくつかの単語は他の単語よりも頻繁に現れますが、それは問題ではなく、繰り返される重要な用語を含むテキストでは普通のことです。",
            "g" : "出現頻度が他の言葉よりも非常に高い言葉があることは、冗長性や語彙の多様性の欠如を示す可能性があります。",
            "h" : "総単語数: ",
            "j" : "総文字数: ",
            "k" : "総文数: ",
            "l" : "PDFファイルを選択",
            "m" : "PDFファイル",
            "n" : "テキストの場合は1、PDFの場合は2を入力してください",
            "o" : "ファイルが選択されていません。",
            "p" : "PDF処理中にエラーが発生しました。",
            "q" : "無効なオプションです。1または2を試してください。",
            "id_sinonimos" : 4}