def mensajes_por_idioma(idioma_i):
    #Cambia el idioma de la interfaz obedeciendo el botón oprimido
    match idioma_i:
        case 1:
            return{
            "usar": "Use now",
            "idioma": "ENGLISH",
            "soporte_cliente": "Customer Support",
            "puedes_ver": "Remember to include a text with more than 100 words, so the page can give you a better analysis, as it's programmed for that purpose.",
            "analizar": "Analyze",
            "nada": "There's no synonyms' group found",
            "varianza":"Variation in your text",
            "analizador": "Text analyzer",
            "tit1":"Frequency of the most common words",
            "globalizacion": "Text globalization",
            "capacidad": "Ability to read multiple languages",
            "contador": "Counter",
            "top10":"Most Frequent Words (Top 10)",
            "palabra":"Word",
            "veces":"times",
            "comentario":"Comment",
            "considera":"You may consider:",
            "yausaste":"You already used: ",
            "noencontrado":"but no synonyms were found.",
            "char_counter":"Character counter",
            "caracteres": "Characters, phrases, and words",
            "contador_caract": "Character counter",
            "sugerencias": "Synonym suggestions",
            "detectado": "Detected language:",
            "palabras": "Total words:",
            "letras": "Total letters",
            "frases": "Total phrases:",
            "resultado": "Analysis result",
            "moda": "Fashion word:",
            "ver_mas": "See more",
            "generador_graf": "Graph generator",
            "corrector": "Text corrector",
            "muletillas": "Good use of filler words",
            "funciones": "Best functions",
            "x": "Enter the text to analyze: ",
            "y" : "is present in",
            "z" :"of the text, you use it too much, look for replacement synonyms :c.",
            "a" :"of the text, you should look for some synonym for that word :c.",
            "b": "of the text, you do not use it as often, but you could make some changes.",
            "d" : "of the text, you don't use it very often :D.",
            "e" : "Your text has a varied vocabulary and a fluid writing style.",
            "f": "Some words appear more than others, but it's not problematic, it's normal in texts with repeated key terms.",
            "g" : "There are words that appear with a frequency much higher than the rest, which may indicate redundancy or lack of variety in vocabulary.",
            "h" : "Total words: ",
            "j" : "Total letters: ",
            "k" : "Total sentences: ",
            "l" : "Text",
            "m" : "PDF file",
            "n" : "Cont+ accepts .txt or .pdf",
            "no" : "No language detected",
            "p" : "Error processing PDF",
            "q" : "Invalid option; try 1 or 2",
            "id_sinonimos" : 1}
        case 2:
            return {
            "usar": "Usar ahora",
            "idioma": "ESPAÑOL",
            "tit1":"Frecuencia de las palabras más comunes",
            "analizar": "Analizar",
            "nada": "No se encontró ningún grupo de sinónimos",
            "soporte_cliente": "Soporte al cliente",
            "puedes_ver" :"Recuerda poner un texto con más de 100 palabras, de esa manera la página podrá darte un mejor análisis, pues está programada para ello.",
            "analizador":"Analizador de textos",
            "globalizacion":"Globalización de textos",
            "capacidad": "Capacidad de leer idiomas varios",
            "contador": "Contador",
            "varianza":"Varianza en tu texto",
            "top10":"Palabras más frecuentes (Top 10)",
            "palabra":"Palabra",
            "veces":"veces",
            "comentario":"Comentario",
            "considera":"Puedes considerar:",
            "yausaste":"Ya usaste: ",
            "noencontrado":"pero no se encontraron sinónimos.",
            "nohay":"No hay sugerencias de sinónimos.",
            "caracteres": "Carácteres, frases y palabras",
            "contador_caract":"Contador de carácteres",
            "sugerencias":"Sugerencias de sinónimos",
            "detectado" :"Idioma detectado:",
            "palabras" :"Total de palabras:",
            "letras" :"Total de letras",
            "frases" :"Total de frases:",
            "resultado" :"Resultado del análisis",
            "moda" :"Palabra moda:",
            "ver_mas":"Ver más",
            "generador_graf":"Generador de gráficas",
            "corrector": "Corrector de textos",
            "muletillas": "Buen uso de muletillas",
            "funciones": "Mejores funciones",
            "x" : "Ingrese el texto a analizar: ",
            "y" : "está presente en el",
            "z" : "del texto, la usas demasiado, busca sinónimos de reemplazo :c.",
            "a" : "del texto, deberías buscar algún sinónimo para dicha palabra :c.",
            "b" : "del texto, no lo usas con tanta frecuencia, pero podrías realizar algún cambio.",
            "d" : "del texto, no lo usas con mucha frecuencia :D.",
            "e" : "Tu texto tiene un vocabulario variado y un estilo de escritura fluido.",
            "f" : "Algunas palabras aparecen más que otras, pero no es problemático, es normal en textos con términos clave repetidos.",
            "g" : "Hay palabras que aparecen con una frecuencia muy superior al resto, puede indicar redundancia o falta de variedad en el vocabulario.",
            "h" : "Total de palabras: ",
            "j" : "Total de letras: ",
            "k" : "Total de frases: ",
            "l" : "Texto",
            "m" : "Archivos PDF",
            "n" : "Cont+ acepta .txt y .pdf",
            "no" : "No se detectó idioma",
            "p" : "Error al procesar el PDF:",
            "q" : "Opción no válida. Intente con 1 o 2.",
            "id_sinonimos" : 2,}
        case 3:
            return {
            "usar": "Usar agora",
            "idioma": "PORTUGUÊS",
            "analizar": "analisar",
            "soporte_cliente": "Suporte ao cliente",
            "puedes_ver" :"Lembre-se de incluir um texto com mais de 100 palavras, para que a página possa lhe dar uma melhor análise, pois ela é programada para isso.",
            "analizador":"Analisador de texto",
            "varianza": "Variação no seu texto",
            "globalizacion":"Globalização de texto",
            "capacidad": "Capacidade de ler vários idiomas",
            "contador": "Contador",
            "caracteres": "Caracteres, frases e palavras",
            "nada": "Não foi encontrado nenhum grupo de sinônimos",
            "palabra":"Palavra",
            "veces":"vezes",
            "comentario":"Comentário",
            "considera":"Você pode considerar:",
            "yausaste":"Você já usou:",
            "noencontrado":"mas nenhum sinônimo foi encontrado.",
            "top10":"Palavras Mais Frequentes (Top 10)",
            "contador_caract": "Contador de caracteres",
            "sugerencias": "Sugestões de sinônimos",
            "detectado": "Idioma detectado:",
            "palabras": "Total de palavras:",
            "letras": "Total de letras",
            "frases": "Total de frases:",
            "resultado": "Resultado da análise",
            "tit1":"Frequência das palavras mais comuns",
            "moda": "Palavra da moda:",
            "ver_mas": "Veja mais",
            "generador_graf": "Gerador de gráficos",
            "corrector": "Corretor de texto",
            "muletillas": "Bom uso de palavras de preenchimento",
            "funciones": "Melhores funções",
            "x" : "Digite o texto a ser analisado: ",
            "y" : "está presente em",
            "z" : "do texto, você a usa demais, procure sinônimos de substituição :c.",
            "a" : "do texto, você deveria procurar algum sinônimo para essa palavra :c.",
            "b" : "do texto, você não o usa com tanta frequência, mas poderia fazer alguma alteração.",
            "d" : "del texto, você não o usa com muita frequência :D.",
            "e" : "Seu texto tem um vocabulário variado e um estilo de escritura fluido.",
            "f" : "Algumas palavras aparecem mais do que outras, mas não é problemático, é normal em textos com termos-chave repetidos.",
            "g" : "Há palavras que aparecem com uma frequência muito superior ao resto, isso pode indicar redundância ou falta de variedade no vocabulário.",
            "h" : "Total de palavras: ",
            "j" : "Total de letras: ",
            "k" : "Total de frases: ",
            "l" : "Texto",
            "m" : "Arquivo PDF",
            "n" : "Cont+ aceita .txt e .pdf",
            "no": "Nenhum idioma detectado",
            "o" : "Nenhum arquivo selecionado",
            "p" : "Erro ao processar o PDF",
            "q" : "Opção inválida; tente 1 ou 2",
            "id_sinonimos" : 3}
        case 4:
            return {
            "usar": "今すぐ使う",
            "idioma": "日本語",
            "analizar": "分析する",
            "soporte_cliente": "カスタマーサポート",
            "puedes_ver" :"ページはその目的のためにプログラムされているため、より詳細な分析が行えるよう、100 語以上のテキストを含めるようにしてください。",
            "analizador":"テキストアナラ​​イザー",
            "tit1":"最も一般的な単語の頻度",
            "globalizacion":"テキストのグローバリゼーション",
            "capacidad": "複数言語の読み取り能力",
            "contador": "カウンター",
            "palabra":"単語",
            "veces":"回",
            "comentario":"コメント",
            "nada": "同義語のグループが見つかりません",
            "considera":"次の単語を検討してください:",
            "yausaste":"次の単語を既に使用しています:",
            "noencontrado":"ただし、同義語は見つかりませんでした。",
            "top10":"最もよく使われる単語（上位10語）",
            "caracteres": "文字、フレーズ、単語",
            "contador_caract": "文字数カウンター",
            "varianza": "テキストのバリエーション",
            "sugerencias": "同義語の候補",
            "detectado": "検出された言語:",
            "palabras": "合計単語数:",
            "letras": "合計文字数",
            "frases": "合計フレーズ数:",
            "resultado": "分析結果",
            "moda": "ファッションワード:",
            "ver_mas": "もっと見る",
            "generador_graf": "グラフジェネレーター",
            "corrector": "テキストコレクター",
            "muletillas": "適切なフィラーワードの使用",
            "funciones": "最適な関数",            
            "x" : "分析するテキストを入力してください: ",
            "y" : "テキストの",
            "z" : "に存在します。使いすぎです。代替の同義語を探してください。:c",
            "a" : "に存在しているので、同義語を探すべきです。:c",
            "b" : "に存在しますが、それほど頻繁に使用していませんが、いくつかの変更を行うことができるかもしれません。",
            "d" : "に存在していますが、あまり頻繁には使いません。 :D",
            "e" : "あなたのテキストは多様な語彙と流れるような文体を持っています。",
            "f" : "いくつかの単語は他の単語よりも頻繁に現れますが、それは問題ではなく、繰り返される重要な用語を含むテキストでは普通のことです。",
            "g" : "出現頻度が他の言葉よりも非常に高い言葉があることは、冗長性や語彙の多様性の欠如を示す可能性があります。",
            "h" : "総単語数: ",
            "j" : "総文字数: ",
            "k" : "総文数: ",
            "l" : "文章",
            "m" : "PDFファイル",
            "n" : "Cont+は.txtと.pdfを受け入れます",
            "no" : "言語が検出されませんでした",
            "o" : "ファイルが選択されていません。",
            "p" : "PDF処理中にエラーが発生しました。",
            "q" : "無効なオプションです。1または2を試してください。",
            "id_sinonimos" : 4}